from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

from ui.new2 import NewWindow
from ui.newbutton import Ui_Form


class Ui_MainWindow(object):

    def __init__(self):
        self.window = None

    def setupUi(self, MainWindow):
        self.window = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 430, 431, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 501, 391))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("resources/test.jpg"))
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 21))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        self.menuCompany = QtWidgets.QMenu(self.menubar)
        self.menuCompany.setObjectName("menuCompany")
        self.menuAccountant = QtWidgets.QMenu(self.menubar)
        self.menuAccountant.setObjectName("menuAccountant")
        self.menuCustomer = QtWidgets.QMenu(self.menubar)
        self.menuCustomer.setObjectName("menuCustomer")
        self.menuVendor = QtWidgets.QMenu(self.menubar)
        self.menuVendor.setObjectName("menuVendor")
        self.menuBank = QtWidgets.QMenu(self.menubar)
        self.menuBank.setObjectName("menuBank")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuAccoounts_Taxes = QtWidgets.QMenu(self.menuReport)
        self.menuAccoounts_Taxes.setObjectName("menuAccoounts_Taxes")
        self.menuFinancials = QtWidgets.QMenu(self.menuReport)
        self.menuFinancials.setObjectName("menuFinancials")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionNew_Company = QtWidgets.QAction(MainWindow)
        self.actionNew_Company.setObjectName("actionNew_Company")
        self.actionNew_Company.triggered.connect(self.on_action_new)

        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionBack_Up = QtWidgets.QAction(MainWindow)
        self.actionBack_Up.setObjectName("actionBack_Up")
        self.actionSingle_User = QtWidgets.QAction(MainWindow)
        self.actionSingle_User.setObjectName("actionSingle_User")
        self.actionUtilities = QtWidgets.QAction(MainWindow)
        self.actionUtilities.setObjectName("actionUtilities")
        self.actionLog_off = QtWidgets.QAction(MainWindow)
        self.actionLog_off.setObjectName("actionLog_off")

        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.triggered.connect(self.on_action_exit)

        self.actionMy_Company = QtWidgets.QAction(MainWindow)
        self.actionMy_Company.setObjectName("actionMy_Company")
        self.actionSnap_Shot = QtWidgets.QAction(MainWindow)
        self.actionSnap_Shot.setObjectName("actionSnap_Shot")
        self.actionChart_of_Accounts = QtWidgets.QAction(MainWindow)
        self.actionChart_of_Accounts.setObjectName("actionChart_of_Accounts")
        self.actionClosing_Date = QtWidgets.QAction(MainWindow)
        self.actionClosing_Date.setObjectName("actionClosing_Date")
        self.actionPlan_Budget = QtWidgets.QAction(MainWindow)
        self.actionPlan_Budget.setObjectName("actionPlan_Budget")
        self.actionUsers = QtWidgets.QAction(MainWindow)
        self.actionUsers.setObjectName("actionUsers")
        self.actionEntity = QtWidgets.QAction(MainWindow)
        self.actionEntity.setObjectName("actionEntity")
        self.actionJournal = QtWidgets.QAction(MainWindow)
        self.actionJournal.setObjectName("actionJournal")
        self.actionReconcile = QtWidgets.QAction(MainWindow)
        self.actionReconcile.setObjectName("actionReconcile")
        self.actionItem_List = QtWidgets.QAction(MainWindow)
        self.actionItem_List.setObjectName("actionItem_List")
        self.actionCustomer_Center = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Center.setObjectName("actionCustomer_Center")
        self.actionCreate_Estimate = QtWidgets.QAction(MainWindow)
        self.actionCreate_Estimate.setObjectName("actionCreate_Estimate")
        self.actionCreate_Invoice = QtWidgets.QAction(MainWindow)
        self.actionCreate_Invoice.setObjectName("actionCreate_Invoice")
        self.actionCreate_Sales_Receipt = QtWidgets.QAction(MainWindow)
        self.actionCreate_Sales_Receipt.setObjectName("actionCreate_Sales_Receipt")
        self.actionReceive_Payment = QtWidgets.QAction(MainWindow)
        self.actionReceive_Payment.setObjectName("actionReceive_Payment")
        self.actionCredit_Memo_Refund = QtWidgets.QAction(MainWindow)
        self.actionCredit_Memo_Refund.setObjectName("actionCredit_Memo_Refund")
        self.actionVendor_Center = QtWidgets.QAction(MainWindow)
        self.actionVendor_Center.setObjectName("actionVendor_Center")
        self.actionEnter_bills = QtWidgets.QAction(MainWindow)
        self.actionEnter_bills.setObjectName("actionEnter_bills")
        self.actionPay_Bills = QtWidgets.QAction(MainWindow)
        self.actionPay_Bills.setObjectName("actionPay_Bills")
        self.actionWrite_Cheque = QtWidgets.QAction(MainWindow)
        self.actionWrite_Cheque.setObjectName("actionWrite_Cheque")
        self.actionMake_Deposit = QtWidgets.QAction(MainWindow)
        self.actionMake_Deposit.setObjectName("actionMake_Deposit")
        self.actionTransfunds = QtWidgets.QAction(MainWindow)
        self.actionTransfunds.setObjectName("actionTransfunds")
        self.actionCredit_Card_Charges = QtWidgets.QAction(MainWindow)
        self.actionCredit_Card_Charges.setObjectName("actionCredit_Card_Charges")
        self.actionReconcile_2 = QtWidgets.QAction(MainWindow)
        self.actionReconcile_2.setObjectName("actionReconcile_2")
        self.actionFixed_Asset = QtWidgets.QAction(MainWindow)
        self.actionFixed_Asset.setObjectName("actionFixed_Asset")
        self.actionInvestment = QtWidgets.QAction(MainWindow)
        self.actionInvestment.setObjectName("actionInvestment")
        self.actionLoans = QtWidgets.QAction(MainWindow)
        self.actionLoans.setObjectName("actionLoans")
        self.actionAR_Report = QtWidgets.QAction(MainWindow)
        self.actionAR_Report.setObjectName("actionAR_Report")
        self.actionAP_Report = QtWidgets.QAction(MainWindow)
        self.actionAP_Report.setObjectName("actionAP_Report")
        self.actionBank = QtWidgets.QAction(MainWindow)
        self.actionBank.setObjectName("actionBank")
        self.actionAudit_Trail = QtWidgets.QAction(MainWindow)
        self.actionAudit_Trail.setObjectName("actionAudit_Trail")
        self.actionBalance_Sheet = QtWidgets.QAction(MainWindow)
        self.actionBalance_Sheet.setObjectName("actionBalance_Sheet")
        self.actionProfit_and_Loss = QtWidgets.QAction(MainWindow)
        self.actionProfit_and_Loss.setObjectName("actionProfit_and_Loss")
        self.actionTrial_Balance = QtWidgets.QAction(MainWindow)
        self.actionTrial_Balance.setObjectName("actionTrial_Balance")
        self.menuFILE.addAction(self.actionNew_Company)
        self.menuFILE.addAction(self.actionOpen)
        self.menuFILE.addSeparator()
        self.menuFILE.addAction(self.actionBack_Up)
        self.menuFILE.addAction(self.actionSingle_User)
        self.menuFILE.addAction(self.actionUtilities)
        self.menuFILE.addSeparator()
        self.menuFILE.addAction(self.actionLog_off)
        self.menuFILE.addAction(self.actionExit)
        self.menuCompany.addAction(self.actionMy_Company)
        self.menuCompany.addAction(self.actionSnap_Shot)
        self.menuCompany.addSeparator()
        self.menuCompany.addAction(self.actionChart_of_Accounts)
        self.menuCompany.addAction(self.actionClosing_Date)
        self.menuCompany.addAction(self.actionPlan_Budget)
        self.menuCompany.addAction(self.actionEntity)
        self.menuCompany.addAction(self.actionItem_List)
        self.menuAccountant.addAction(self.actionJournal)
        self.menuAccountant.addAction(self.actionReconcile)
        self.menuAccountant.addAction(self.actionUsers)
        self.menuAccountant.addSeparator()
        self.menuAccountant.addAction(self.actionFixed_Asset)
        self.menuAccountant.addAction(self.actionInvestment)
        self.menuAccountant.addAction(self.actionLoans)
        self.menuCustomer.addAction(self.actionCustomer_Center)
        self.menuCustomer.addSeparator()
        self.menuCustomer.addAction(self.actionCreate_Estimate)
        self.menuCustomer.addAction(self.actionCreate_Invoice)
        self.menuCustomer.addAction(self.actionCreate_Sales_Receipt)
        self.menuCustomer.addAction(self.actionReceive_Payment)
        self.menuCustomer.addAction(self.actionCredit_Memo_Refund)
        self.menuVendor.addAction(self.actionVendor_Center)
        self.menuVendor.addSeparator()
        self.menuVendor.addAction(self.actionEnter_bills)
        self.menuVendor.addAction(self.actionPay_Bills)
        self.menuBank.addAction(self.actionWrite_Cheque)
        self.menuBank.addAction(self.actionMake_Deposit)
        self.menuBank.addAction(self.actionTransfunds)
        self.menuBank.addAction(self.actionCredit_Card_Charges)
        self.menuBank.addSeparator()
        self.menuBank.addAction(self.actionReconcile_2)
        self.menuAccoounts_Taxes.addAction(self.actionTrial_Balance)
        self.menuFinancials.addAction(self.actionBalance_Sheet)
        self.menuFinancials.addAction(self.actionProfit_and_Loss)
        self.menuReport.addAction(self.menuFinancials.menuAction())
        self.menuReport.addSeparator()
        self.menuReport.addAction(self.actionAR_Report)
        self.menuReport.addAction(self.actionBank)
        self.menuReport.addAction(self.actionAP_Report)
        self.menuReport.addSeparator()
        self.menuReport.addAction(self.menuAccoounts_Taxes.menuAction())
        self.menuReport.addAction(self.actionAudit_Trail)
        self.menubar.addAction(self.menuFILE.menuAction())
        self.menubar.addAction(self.menuCompany.menuAction())
        self.menubar.addAction(self.menuAccountant.menuAction())
        self.menubar.addAction(self.menuCustomer.menuAction())
        self.menubar.addAction(self.menuVendor.menuAction())
        self.menubar.addAction(self.menuBank.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Invoice"))
        self.pushButton_2.setText(_translate("MainWindow", "Bills"))
        self.pushButton_3.setText(_translate("MainWindow", "Journal"))
        self.pushButton_4.setText(_translate("MainWindow", "Bank"))
        self.pushButton_5.setText(_translate("MainWindow", "Report"))
        self.menuFILE.setTitle(_translate("MainWindow", "FILE"))
        self.menuCompany.setTitle(_translate("MainWindow", "Company"))
        self.menuAccountant.setTitle(_translate("MainWindow", "Accountant"))
        self.menuCustomer.setTitle(_translate("MainWindow", "Customer"))
        self.menuVendor.setTitle(_translate("MainWindow", "Vendor"))
        self.menuBank.setTitle(_translate("MainWindow", "Bank"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuAccoounts_Taxes.setTitle(_translate("MainWindow", "Accoounts & Taxes"))
        self.menuFinancials.setTitle(_translate("MainWindow", "Financials"))
        self.actionNew_Company.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionBack_Up.setText(_translate("MainWindow", "Back-Up"))
        self.actionSingle_User.setText(_translate("MainWindow", "Single User"))
        self.actionUtilities.setText(_translate("MainWindow", "Utilities"))
        self.actionLog_off.setText(_translate("MainWindow", "Log off"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionMy_Company.setText(_translate("MainWindow", "My Company"))
        self.actionSnap_Shot.setText(_translate("MainWindow", "Snap-Shot"))
        self.actionChart_of_Accounts.setText(_translate("MainWindow", "Charts of Accounts"))
        self.actionClosing_Date.setText(_translate("MainWindow", "Closing Date"))
        self.actionPlan_Budget.setText(_translate("MainWindow", "Plan/Budget"))
        self.actionUsers.setText(_translate("MainWindow", "Users"))
        self.actionEntity.setText(_translate("MainWindow", "Entity"))
        self.actionJournal.setText(_translate("MainWindow", "Journal"))
        self.actionReconcile.setText(_translate("MainWindow", "Reconcile"))
        self.actionItem_List.setText(_translate("MainWindow", "Item List"))
        self.actionCustomer_Center.setText(_translate("MainWindow", "Customer Center"))
        self.actionCreate_Estimate.setText(_translate("MainWindow", "Estimate/Pro-Forma"))
        self.actionCreate_Invoice.setText(_translate("MainWindow", "Invoice"))
        self.actionCreate_Sales_Receipt.setText(_translate("MainWindow", "Sales Receipt"))
        self.actionReceive_Payment.setText(_translate("MainWindow", "Receive Payment"))
        self.actionCredit_Memo_Refund.setText(_translate("MainWindow", "Credit Memo/Refund"))
        self.actionVendor_Center.setText(_translate("MainWindow", "Vendor Center"))
        self.actionEnter_bills.setText(_translate("MainWindow", "Bills"))
        self.actionPay_Bills.setText(_translate("MainWindow", "Pay Bills"))
        self.actionWrite_Cheque.setText(_translate("MainWindow", "Write Cheque"))
        self.actionMake_Deposit.setText(_translate("MainWindow", "Make Deposit"))
        self.actionTransfunds.setText(_translate("MainWindow", "Transfer"))
        self.actionCredit_Card_Charges.setText(_translate("MainWindow", "Credit Card Charges"))
        self.actionReconcile_2.setText(_translate("MainWindow", "Reconcile"))
        self.actionFixed_Asset.setText(_translate("MainWindow", "Fixed Asset"))
        self.actionInvestment.setText(_translate("MainWindow", "Investment"))
        self.actionLoans.setText(_translate("MainWindow", "Loans"))
        self.actionAR_Report.setText(_translate("MainWindow", "Receivables"))
        self.actionAP_Report.setText(_translate("MainWindow", "Bank"))
        self.actionBank.setText(_translate("MainWindow", "Payables"))
        self.actionAudit_Trail.setText(_translate("MainWindow", "Audit Trail"))
        self.actionBalance_Sheet.setText(_translate("MainWindow", "Balance Sheet"))
        self.actionProfit_and_Loss.setText(_translate("MainWindow", "Profit and Loss"))
        self.actionTrial_Balance.setText(_translate("MainWindow", "Trial Balance"))

    def on_action_new(self):
        main_window = QtWidgets.QMainWindow(parent=self.window, flags=Qt.Window)
        new_window = Ui_Form()
        new_window.setupUi(main_window)
        main_window.show()

    def on_action_exit(self):
        exit(0)
